### ISSUE TITLE
[Issue/Bug] Stuck in flexible corridor connect mode

### ISSUE THREAD

**Issue by TacoCraftxD** [Nils277/KerbalPlanetaryBaseSystems#103]
When entering into corridor connect mode, and then using vesselmover's "Spawn Vessel" tool you get stuck in corridor connect. I think this is because when spawning a new vessel you focus it, and then i managed to kill the kerbal that originally started it. And so i am stuck in connect mode.
![Example](https://user-images.githubusercontent.com/32072697/59914040-cadbb380-9419-11e9-8825-4f553056945e.png)
Look at the Light/Gear/Brake buttons for example

I am in creative

**Comment by TacoCraftxD** [comment]
The ESC key doesn't work either, i have to use the button on the top

**Comment by TacoCraftxD** [comment]
Save:
[Bases1.zip](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/3314202/Bases1.zip)

**Comment by Nils277** [comment]
Thanks for the bug report. :-)
However, this is not a bug caused by KPBS, it is a bug caused by KAS because all the functionality from the flexible corridors is done by KAS.
Therefore i can't fix this bug, it can only be fixed in KAS. 
Please report it here: [KAS/issues](https://github.com/ihsoft/KAS/issues)

**Comment by TacoCraftxD** [comment]
Got it, thanks 👍
