### ISSUE TITLE
Can i add your mod in the my mod download dependencies

### ISSUE THREAD

**Issue by dogevspenguin** [Nils277/KerbalPlanetaryBaseSystems#111]
I want to make a mod about colonization but it require the original Kerbal Planetary Base Inc and can i put it in the original download(As a seperate folder)

**Comment by Nils277** [comment]
You can add KPBS as a dependency, when you mod is not only a compilation of other mods without adding anything new and unique to it.
If you add KPBS, please make sure that other added mods are compatible and all are in the latest (compatible) version. Also keep all mods up to date to ensure best compatibility.
Please also add an info in the readme, and your post in the Forums, that you are the primary person to contact when error or problems arise with compatibility issues etc. with mods installed as dependency of your mod.
In the past it showed that very often the original authors were flooded with problems that were caused by mod compilations of mods that were not compatible with each other or outdated.

**Comment by dogevspenguin** [comment]
Ok in the download there will only be my mod your mod(As a depencie)and module manager
