### ISSUE TITLE
Mod not loading when correctly placed in folder

### ISSUE THREAD

**Issue by JhonforgeGaming** [Nils277/KerbalPlanetaryBaseSystems#6]
I have noticed that me as well as some of my friends couldn't get this mod to work. We placed it correctly in the Plugins/Gamedata folder and nothing showed up. I have used this mod before and I really like it but now it seams to not work. We use 1.1 and would like this to be fixed. Thanks!

**Comment by Nils277** [comment]
Weird. Have you deleted the old "PlanetaryBaseInc" folder before installing? Versions before version 1.0 of this mod had a different folder structure and therefore an old plugin dll might be the problem.
Otherwise i would need the log ksp creates to see what is wrong. Look [here](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/) for instructions on the log.
Additionally two screenshots , one of the gamedata folder, and one of the PlanetaryBaseInc folder would be helpful. So i can see of everything is installed.

**Comment by JhonforgeGaming** [comment]
I had lost my old version of KSP when my hard drive failed. when 1.1 came out i installed again so I don't have the old Folder or Plugin data. Here are the Screenshots but with the Log I only Crash when I go over my RAM limit But here it is anyway: Sorry that I couldn't ZIP the Log WinZip won't Let me... 
![gamedata](https://cloud.githubusercontent.com/assets/19367475/15278138/c72598bc-1ad9-11e6-8e21-b5d4ebb9cc0d.png)

![planetarybaseinc](https://cloud.githubusercontent.com/assets/19367475/15278139/c8b2d44c-1ad9-11e6-9d1b-046369ee2682.png)

[output_log.txt](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/265406/output_log.txt)

**Comment by Nils277** [comment]
The folder structure and everything looks okay. There is one line in the log, that might be causing the problem:
`[KPBS] ERROR EXC loading Images: Could not find a part of the path "C:\Games\Kerbal Space Program 1.1\GameData\PlanetaryBaseInc\BaseSystem\Icons\KPBSicon.png".`
Can you take a look at the path mentioned and see of the "KPBSicon.png" exists?

Normally this error shouldn't cause the parts to disappear, (only the custom categories will not function) But i guess it is a symptom of another problem, i don't see yet.

**Comment by Nils277** [comment]
Forget my earlier comment....i did not look at the path

There are a lot of messages about not being able to find the models:
e.g.: `Model load error in 'C:\Games\Kerbal Space Program 1.1\Plugins\GameData\PlanetaryBaseInc\BaseSystem\Spaces\Airlocks_internal\airlock_end_g_internal.mu'`
The Folder for the mods should **not** be installed in _Kerbal Space Program 1.1\Plugins\GameData\PlanetaryBaseInc_ but in
_Kerbal Space Program 1.1\GameData\PlanetaryBaseInc_

This is the case for all mods since version 0.20 of KSP. I really wonder why some of the mods do work when they are installed in that directrory.

**Comment by JhonforgeGaming** [comment]
Ah Ok let me change that. As for some mods still working in that directory Could it be that their somehow able to work in both? I mean the only thing they would need is a file out in the directory it is supposed to be in and then that file could point it to where the bulk of the mod is.

**Comment by Nils277** [comment]
that would be nearly impossible. I have to specify the location of the models in every config file for the parts. (This must be done when multiple parts share one folder so save resources).
There are some mods that will work, when they don't load custom images or only have one part per folder. But the chance is high, that at least some parts will be missign ;)
