### ISSUE TITLE
CC-BY-NC-SA and CC-BY-SA are incompatible

### ISSUE THREAD

**Issue by Anth0rx** [Nils277/KerbalPlanetaryBaseSystems#60]
As mentioned in https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses the CC-BY-NC-SA and CC-BY-SA licenses are incompatible. As of my understanding you cannot use CC-BY-NC-SA licensed material and release it under CC-BY-SA.

**Comment by Nils277** [comment]
I have to excuse for my last comment. Looking at the Main site of this mod it shows to have the CC-BY-SA license. Which i cannot understand. I would have never chosen the CC-BY-SA.
What makes this worse is that it actually links to the license file for the source code, which in fact is the Apache 2.0 license (since CC licenses are not meant for code)

Will have to try to either change that to CC-BY-NC or better remove the information altogether

**Comment by Nils277** [comment]
Fixed by 393e5df2c1c71a1341d7b9ca99d7ea791b765357
I really wonder why this file was selected for the license at the first place, since it did not resemle the common license name.
