### ISSUE TITLE
Parts Going through other Parts

### ISSUE THREAD

**Issue by JhonforgeGaming** [Nils277/KerbalPlanetaryBaseSystems#7]
I know I recently had an issue resolved but i found one thing that is bothersome that i looked to find a fix for but couldn't. When I go to launch a Base whether it is part of something or not Half of the Base goes through Everything else but the ground. Please help me I want a Mun Base!
Forgot to Mention that it only happens when I have a Habitat attached!

**Comment by Nils277** [comment]
So you say, that the base does not collide with other crafts. Is that right? But it does collide with the ground?
That sounds really weird and i have never heard of this issue. What habitat are you speaking of, the MK1 or the MK2? If it is the MK2 do you habe the same problem when the greenhouse or the laboratory are used?
One idea might be, to delete the "PartDatabase.cfg" and the "Physics.cfg" files from the main folder of KSP. The game will regenerate them at the next start. Might be that some physics setting got invalid for some reason. Otherwise i would again need a log to see what is happening.

**Comment by JhonforgeGaming** [comment]
what happens is that I will load the craft and before I'm allowed to do any controls the main habitat no matter what habitats it is will fall away from the other craft with anything attached to the top facing side.

**Comment by Nils277** [comment]
The output_log.txt ends with a crash in the editor. I can't see what is happening when the flight starts.
Maybe the .craft file from Base 1 would help.
It's in _saves\mods\Ships\VAB\Base 1.craft_

**Comment by JhonforgeGaming** [comment]
I don't have the base 1 file because i renamed it to Base 2 and so here it is:


[Base 2.txt](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/274521/Base.2.txt)

**Comment by Nils277** [comment]
I'm very sorry to say, but the base linked works fine on my machine. Can you send me the KSP.log file that is located in the same folder as the KSP executable, after you launched the base on the launch pad? It's the last thing i can look into to maybe find out the problem.

**Comment by JhonforgeGaming** [comment]
[new.txt](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/276059/new.txt)

had to change file name but other than that it is all there.

**Comment by Nils277** [comment]
Okay, i notices one small first thing. It seems you are still using the prerelease version of KSP and not the newest version 1.1.2. This might be a first clue for the error and be the reason why loading the shaders for the IVAs caused errors. 
You have to manually opt out of the beta program to get the new full releases that are currently more up to date than the beta.
I can't say much more, because the log ends directly after loading the game, there is not logged that a game was loaded or a switch into a flight scene took place. But that is what i need to see.

**Comment by JhonforgeGaming** [comment]
It was that I didn't update...everything works...Carry on

**Comment by Nils277** [comment]
Cool. Good to hear it works :smiley:  
One less bug to worry about.
